variables:
   DEBIAN_X86_BUILD_BASE_IMAGE: "debian/x86_build-base"
   DEBIAN_BASE_TAG: "2022-04-24-libdrm"

   DEBIAN_X86_BUILD_IMAGE_PATH: "debian/x86_build"
   DEBIAN_BUILD_TAG: "2022-05-12-DirectX-Headers"

   DEBIAN_X86_TEST_BASE_IMAGE: "debian/x86_test-base"

   DEBIAN_X86_TEST_IMAGE_PATH: "debian/x86_test-gl"
   DEBIAN_X86_TEST_GL_TAG: "2022-06-09-piglit-update"
   DEBIAN_X86_TEST_VK_TAG: "2022-06-14-vkd3d-proton"

   FEDORA_X86_BUILD_TAG: "2022-04-24-spirv-tools-5"
   KERNEL_ROOTFS_TAG: "2022-06-09-piglit-update"

   WINDOWS_X64_VS_PATH: "windows/x64_vs"
   WINDOWS_X64_VS_TAG: "2022-06-15-vs-winsdk"

   WINDOWS_X64_BUILD_PATH: "windows/x64_build"
   WINDOWS_X64_BUILD_TAG: "2022-06-15-vs-winsdk"

   WINDOWS_X64_TEST_PATH: "windows/x64_test"
   WINDOWS_X64_TEST_TAG: "2022-06-15-vs-winsdk"
